spring:
  application:
    name: AiDevs3
tasks:
  baseUrl: https://mock.com
  apiKey: abc
langchain4j:
  open-ai:
    chat-model:
      api-key: abc
      model-name: gpt-4o-mini
      log-requests: true
      log-responses: true
