spring:
  application:
    name: AiDevs3
#  main:
#    lazy-initialization: true
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4jnew
tasks:
  baseUrl: ${AIDEVS_TASKS_URL}
  apiKey: ${AIDEVS_API_KEY}
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: gpt-4o
      log-requests: true
      log-responses: true
logging:
  level:
    dev:
      langchain4j: DEBUG
      ai4j:
        openai4j: DEBUG
